### PR TITLE
Patch to fix linking of pocketsphinx libs into jni on Linux

### PR DESCRIPTION
**Pull request by andrenatal**

### CODE REVIEW

**Comment by andrenatal** [comment]
@kdavis-mozilla Can you please take a look?

**Comment by kdavis-mozilla** [comment]
Will this work if someone does an install with a zip file as for example described here[[1]](https://github.com/mozilla/openhab-distro#getting-started)?

It seems like this approach will work for the test, but not work as soon as someone moves the location of the pocketsphinx libraries as would occur is someone installed using a zip file.

**Comment by andrenatal** [comment]
I'm closing this. 
It was fixed in this [commit](https://github.com/mozilla/pocketsphinx/commit/dfd034367e847d5c224b31ee768a0385bd457a41)

**Comment by andrenatal** [comment]
Regarding running from a zip file, assuming the classes will be loaded from org.eclipse.smarthome.io.voice bundle root, [this should fix](https://github.com/mozilla/pocketsphinx/blob/master/swig/java/pom.xml#L66)

**Pull request closed without merging**
